name: Build Kivy Android APK

on:
  push:
    branches:
      - main  # Adjust branch as needed
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3  # Updated to v3 for Node 16 support

    - name: Set up Python
      uses: actions/setup-python@v4  # Updated to v4 for Node 16 support
      with:
        python-version: "3.9"  # Adjust based on your app's requirements

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libffi-dev libssl-dev
        sudo apt install -y build-essential libsqlite3-dev
        sudo apt install -y zlib1g-dev libgmp-dev libmpfr-dev libmpc-dev
        sudo apt install -y openjdk-8-jdk
        pip install --upgrade pip setuptools cython
        pip install buildozer

    - name: Install Android SDK, NDK & Buildozer Requirements
      run: |
        sudo apt install -y libgl1-mesa-dev
        sudo apt install -y unzip
        buildozer android sdk install

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: MyCustomApp.apk
        path: ./bin/*.apk
